# 
star1: 
    linelist: /home/FASMA-synthesis/FASMA/rawLinelist/linelist.lst 
    teff: 5777
    logg: 4.44
    feh: 0.0
    vt: 1.0
    vmac: 3.21
    vsini: 1.90
    model: apogee_kurucz
    save: False
    element: False
    fix_teff: False
    fix_logg: False
    fix_feh: False
    fix_vt: False
    fix_vmac: False
    fix_vsini: False
    plot: True
    plot_res: False
    damping: 1
    step_wave: 0.01
    step_flux: 3.0
    minimize: True
    refine: False
    observations: /home/FASMA-synthesis/FASMA/spectra/Sun_HARPS.fits 
    intervals_file: /home/FASMA-synthesis/FASMA/rawLinelist/intervals.lst 
    snr: null
    resolution: null
    limb: 0.6

